#!/usr/bin/env node
/**
 * Pre-extracts icon `<symbol>` definitions from the SLDS utility sprite
 * into a static TypeScript module (src/utils/iconData.ts). This lets
 * Icons.tsx render each icon's paths inline as children of a fresh
 * <svg>, bypassing `<use href="#id">` entirely.
 *
 * Why: <use> references have a zoo of cross-browser/iframe/CSP failure
 * modes (shadow-DOM isolation, display:none visibility rules, external
 * file CSS inheritance, etc.) that leave icons invisible inside the
 * SFMC Content Builder iframe. Embedding the path data directly is the
 * only rendering path that works everywhere.
 *
 * Run: `node scripts/generateIconData.js`
 * Also wired into `npm run build` via the `prebuild` script.
 */
const fs = require('node:fs');
const path = require('node:path');

const SPRITE = path.join(
  __dirname,
  '..',
  'public',
  'assets',
  'icons',
  'utility-sprite',
  'svg',
  'symbols.svg',
);
const OUT = path.join(__dirname, '..', 'src', 'utils', 'iconData.ts');

// Icons referenced by the app (keep in sync with Icons.tsx).
const NEEDED = [
  'share', 'download', 'close', 'left_align_text', 'center_align_text',
  'right_align_text', 'formula', 'image', 'move', 'success',
  'keyboard_dismiss', 'error', 'settings', 'help', 'desktop',
  'phone_portrait', 'open_folder', 'opened_folder', 'new', 'save', 'edit',
  'delete', 'search', 'chevronright', 'chevronleft', 'chevrondown',
  'file', 'back', 'list', 'copy', 'add',
  // Also used via direct <use xlinkHref> in ClientApp.tsx.
  'check', 'info', 'layers', 'link', 'palette', 'slider', 'text',
  'upload', 'warning', 'world',
];

const sprite = fs.readFileSync(SPRITE, 'utf8');

// Extract each <symbol id="..." viewBox="..."> ... </symbol>.
// Greedy-safe regex: stop at the closing tag of each symbol.
const symbolRegex = /<symbol\b([^>]*?)>([\s\S]*?)<\/symbol>/gi;

const data = {};
let match;
while ((match = symbolRegex.exec(sprite)) !== null) {
  const attrs = match[1];
  const inner = match[2];
  const idMatch = attrs.match(/\bid="([^"]+)"/);
  const viewBoxMatch = attrs.match(/\bviewBox="([^"]+)"/);
  if (!idMatch) continue;
  const id = idMatch[1];
  if (!NEEDED.includes(id)) continue;
  data[id] = {
    viewBox: viewBoxMatch ? viewBoxMatch[1] : '0 0 520 520',
    content: inner.trim(),
  };
}

const missing = NEEDED.filter((n) => !data[n]);
if (missing.length) {
  console.error(`[generateIconData] Missing icons in sprite: ${missing.join(', ')}`);
  process.exit(1);
}

const header = `// AUTO-GENERATED by scripts/generateIconData.js — do not edit by hand.
// Regenerate with: node scripts/generateIconData.js
// Source: public/assets/icons/utility-sprite/svg/symbols.svg

export interface IconDef {
  viewBox: string;
  content: string;
}

export const ICON_DATA: Record<string, IconDef> = `;

fs.writeFileSync(OUT, header + JSON.stringify(data, null, 2) + ';\n', 'utf8');
console.log(`[generateIconData] Wrote ${Object.keys(data).length} icons -> ${path.relative(process.cwd(), OUT)}`);
